[supervisord]
nodaemon=true

[program:vnc]
command=su - kali -c "vncserver :1 -geometry 1280x800 -depth 24"
autorestart=true

[program:websockify]
command=websockify --web=/usr/share/novnc/ 8080 localhost:5901
autorestart=true
